### ISSUE TITLE
Problème de récupération des obsels (list_obsels)

### ISSUE THREAD

**Issue by plp69** [bmathern/samotraces.js#2]
Lors de l'appel de list_obsels() sur un objet de type Samotraces.KTBS.Trace (uri), la requête pour récupérer les obsels échoue. Il essaye de récupérer des obsels sur l'uri localhost/@obsels au lieu d'utiliser l'uri de la trace (+ @obsels). En regardant les attributs de mon objet (trace), je m'aperçois que obsels_list_uri = "@obsels"

Voici mon code : 
var trace = new Samotraces.KTBS.Trace("http://localhost:8001/base1/t01/");
trace.list_obsels(); // ici cela échoue
De même pour l'utilisation Samotraces.UI.Widgets.TraceDisplayIcons qui utilise aussi list_obsels(), je ne peux pas afficher les obsels.

Pour pouvoir récupérer les obsels, j'ai modifié le code pour qu'il ajoute l'uri de la trace avant le @obsel au lieu d'utiliser le chemin: 
list_obsels: function(begin,end,reverse) {
this.obsel_list_uri = this.uri + this.obsel_list_uri; // ajouté
        if(this.obsel_list_uri === "") {
            console.log("Error in KTBS:Trace:list_obsels() unknown uri");
            return false;
        }
etc...

**Comment by bmathern** [comment]
Depending on the version of the KTBS, the hasObselList property would either return the full URI of the obsel list (in orlder versions of the KTBS) or the relative URI (current behaviour of the KTBS).

**Comment by bmathern** [comment]
Merci d'avoir pris le temps de reporter ce bogue.
Le bogue devrait maintenant être corrigé, quelle que soit la version du KTBS.
